### ISSUE TITLE
Errors in ubuntu touch 

### ISSUE THREAD

**Issue by winstonford** [Thadeuks/Animefetch#5]
Buenas tardes.  Buscando una opción como neofetch, pero con python.. y así es. Gracias. Un buen nombre puede ser: pyfetch

phablet@ubuntu-phablet:~$ python3 -m Animefetch
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/phablet/.local/lib/python3.5/site-packages/Animefetch/__init__.py", line 1, in <module>
    from .script import main
  File "/home/phablet/.local/lib/python3.5/site-packages/Animefetch/script.py", line 15
    user_node = f'{Style.RESET_ALL}{Fore.CYAN+user}{Style.RESET_ALL+"@"}{Fore.CYAN+node}{Style.RESET_ALL}'
                                                                                                         ^
SyntaxError: invalid syntax
phablet@ubuntu-phablet:~$ python3 --version
Python 3.5.2
phablet@ubuntu-phablet:~$

**Comment by Thadeuks** [comment]
Saludos @winstonford !

**Respecto al error:** Por lo que veo hay un error al ejecutar este programa en *ubuntu*, lamentablemente hasta el momento Animefetch solo ha sido **probado y desarrollado en y para Windows 10**, no se ha reportado ningún error en los usuarios con este sistema operativo.

Animefetch tiene como objetivo ser una mejor opción que neofetch para los **usuarios de Windows**, ya que neofetch en este OS tiene una instalación tediosa y una personalización bastante pobre, no fue pensado para usuarios de Linux o MacOS, mis disculpas.

![image](https://user-images.githubusercontent.com/93542549/152547809-6e9f6023-3eef-4377-87ab-2c8c5057924c.png)

Lo único que puedo recomendarte por el momento es **instalar la [última version de python](https://www.python.org/downloads/)** y probar si funciona, agradecería que compartieras el resultado.
 
Aún así, muchas gracias por alertarme de ese error, todavía no estaba seguro si funcionaría las distribuciones Linux, si no es el caso, espero poder crear una version para estos sistemas.

Que tengas buen día :)

**Comment by Thadeuks** [comment]
@winstonford 

**Respecto al nombre:** *Animefetch* Fue nombrado así por su característico arte ASCII. Ya hay algunos programas que intentan replicar a *neofetch* escritos en python, el diferenciador de *Animefetch* es que la información del sistema viene acompañada de un lindo arte ASCII de anime!

![image](https://user-images.githubusercontent.com/93542549/152550178-57ecd898-6a16-4fe8-9588-ee8de89d025e.png)

Y de ahí ese nombre, no planeo cambiarlo.

Saludos! :)
